---
name: Compile the tools

on:
  push:         { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  csharp:
    runs-on: windows-latest
    strategy:
      matrix: { project: [ Seatbelt ] }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build the solution
        run: msbuild /p:Configuration=Release
        working-directory: windows/${{ matrix.project }}

      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.project }}
          path: windows/${{ matrix.project }}/bin/Release/${{ matrix.project }}.exe
          if-no-files-found: error

  bundle:
    runs-on: ubuntu-latest
    needs: csharp
    steps:
      - name: Download csharp artifacts
        uses: actions/download-artifact@v4
        with:
          path: /tmp/bundle/
          pattern: "*"
          merge-multiple: true
    
      - name: Remove the temporary artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: "*"
    
      # ----------------------------------------------
      #   Seatbelt
      # ----------------------------------------------
    
      - name: list bundle
        run: ls -la /tmp/bundle/

      - name: Upload the final artifact
        uses: actions/upload-artifact@v4
        with:
          name: hackpack
          path: /tmp/bundle/
          compression-level: 9
          if-no-files-found: error