---
name: Compile the tools

on:
    push:         { branches: [ main ] }
    pull_request: { branches: [ main ] }

jobs:
    dotnet:
        runs-on: windows-2019
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
                submodules: recursive
            
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 5.0
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: ./windows/seatbelt

            - name: Build the tools
              run: dotnet build --configuration Release
              working-directory: ./windows/seatbelt
