---
name: Compile the tools

on:
    push:         { branches: [ main ] }
    pull_request: { branches: [ main ] }

jobs:
    dotnet:
        runs-on: windows-2019
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
                submodules: recursive
            
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2

            - name: Build the solution
              run: msbuild /p:Configuration=Release
              working-directory: windows/seatbelt
